import renderOperators from "./renderOperators";
import renderNumbers from "./renderNumbers";
import "../assets/css/style.css";
const renderCalc = function () {
  const root = document.querySelector("#root");
  const container = document.createElement("div");
  const screen = document.createElement("div");
  const prev = document.createElement("div");
  const cur = document.createElement("div");
  const operators = renderOperators();
  const numbers = renderNumbers();
  const equal = document.createElement("button");
  const del = document.createElement("button");
  const allClear = document.createElement("button");
  const point = document.createElement("button");
  const numbersContainer = document.createElement("div");
  const acNumContainer = document.createElement("div");
  const acEqContainer = document.createElement("div");

  equal.textContent = "=";
  equal.setAttribute("class", "equal");
  del.textContent = "del";
  del.setAttribute("class", "del");
  allClear.textContent = "AC";
  allClear.setAttribute("class", "allClear");
  point.textContent = ".";
  point.setAttribute("class", "number");
  screen.setAttribute("class", "screen");
  prev.setAttribute("class", "prev-operand");
  cur.setAttribute("class", "cur-operand");
  container.setAttribute("class", "container");
  acNumContainer.setAttribute("class", "acNumContainer");
  acEqContainer.setAttribute("class", "acEqContainer");

  numbersContainer.setAttribute("class", "numContainer");
  numbers.forEach((num) => numbersContainer.appendChild(num));
  numbersContainer.appendChild(point);
  numbersContainer.appendChild(del);
  screen.appendChild(prev);
  screen.appendChild(cur);
  container.appendChild(screen);
  operators.forEach((op) => container.appendChild(op));
  acEqContainer.appendChild(allClear);
  acEqContainer.appendChild(equal);
  acNumContainer.appendChild(numbersContainer);
  acNumContainer.appendChild(acEqContainer);
  container.appendChild(acNumContainer);
  root.appendChild(container);
};
export default renderCalc;
